name: Make package
on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ~1.22

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build 
        run: go build

      - uses: actions/upload-artifact@v4
        with:
          name: nsuite-kmscli-${{ runner.os }}
          path: nsuite-kmscli*

  comfirm:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
      - name: Archive
        run: |
          ls -la *
          for dir in nsuite-kmscli-*
          do
            target=$(basename $dir).zip
            echo "making $target"
            pushd $dir
            chmod +x *
            zip ../$target *
            popd
          done
          ls -la *
